apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opstrack.fullname" . }}-backend
  labels:
    {{- include "opstrack.labels" . | nindent 4 }}
    app: opstrack-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: opstrack-backend
  template:
    metadata:
      labels:
        app: opstrack-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql+psycopg2://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ include "opstrack.fullname" . }}-db:5432/{{ .Values.postgres.database }}

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "opstrack.fullname" . }}-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "opstrack.fullname" . }}-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "opstrack.fullname" . }}-db-secret
                  key: POSTGRES_DB
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
