apiVersion: v1
kind: Service
metadata:
  name: {{ include "opstrack.fullname" . }}-frontend
  labels:
    {{- include "opstrack.labels" . | nindent 4 }}
    app: opstrack-frontend
spec:
  type: NodePort
  selector:
    app: opstrack-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
