apiVersion: v1
kind: Service
metadata:
  name: {{ include "opstrack.fullname" . }}-db
  labels:
    {{- include "opstrack.labels" . | nindent 4 }}
    app: opstrack-db
spec:
  type: ClusterIP
  selector:
    app: opstrack-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
