apiVersion: apps/v1
kind: Deployment
metadata:
  name: opstrack-backend
  namespace: opstrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opstrack-backend
  template:
    metadata:
      labels:
        app: opstrack-backend
    spec:
      containers:
        - name: backend
          image: opstrack-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: opstrack-db-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opstrack-db-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: opstrack-db-secret
                  key: POSTGRES_DB

            - name: DATABASE_URL
              value: postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@opstrack-db:5432/$(POSTGRES_DB)

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
